/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DataBase.DatabaseConnection;
import static GUI.LoginPage.LoggedPlayer;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anjana
 */
public class GameProfilePage extends javax.swing.JFrame {

    String name;
    String email;
    String points;
    String hpoints;
    String second;
    String minute;
    String date;

    /**
     * Creates new form GameProfilePage
     */
    public GameProfilePage() {
        initComponents();
        try {
            DatabaseConnection db = new DatabaseConnection();

            Statement ps = db.getConnect().createStatement();

            ResultSet rs = ps.executeQuery("select point,second,minute,date from point where email='" + LoggedPlayer + "'");

            DefaultTableModel model = (DefaultTableModel) pointTable.getModel();
            model.setRowCount(0);
            while (rs.next()) {

                points = String.valueOf(rs.getInt("point"));
                second = String.valueOf(rs.getInt("second"));
                minute = String.valueOf(rs.getInt("minute"));
                date = rs.getString("date");

                String array[] = {points, second, minute, date};

                model.addRow(array);

            }
            emailLabel.setText("" + LoggedPlayer);

        } catch (Exception ex) {

        }
        try {
            DatabaseConnection db = new DatabaseConnection();
            Statement ps = db.getConnect().createStatement();
            ResultSet rs = ps.executeQuery("select name from user where email='" + LoggedPlayer + "'");

            if (rs.next()) {
                name = rs.getString("name");
            }
            emailLabel.setText("" + name);

        } catch (Exception ex) {

        }
        getMax();
    }

    public void getMax() {
        ArrayList<Integer> list = new ArrayList<Integer>();
        for (int i = 0; i < pointTable.getRowCount(); i++) {
            list.add(Integer.parseInt(pointTable.getValueAt(i, 0).toString()));
        }
        int max = Collections.max(list);
        highLabel.setText("" + max);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        highLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pointTable = new javax.swing.JTable();
        emailLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 50)); // NOI18N
        jLabel2.setText("Point Table");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Highest Point");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        highLabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        highLabel.setForeground(new java.awt.Color(0, 102, 102));
        highLabel.setText("10");
        jPanel1.add(highLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 70, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel5.setText("All Points of");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 130, -1));

        jButton1.setBackground(new java.awt.Color(132, 61, 20));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back ");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 140, 40));

        pointTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        pointTable.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        pointTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Point", "Duration in Seconds", "Duration in Minutes", "Date & Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pointTable.setGridColor(new java.awt.Color(204, 204, 204));
        pointTable.setRowHeight(25);
        pointTable.setRowMargin(0);
        jScrollPane2.setViewportView(pointTable);
        if (pointTable.getColumnModel().getColumnCount() > 0) {
            pointTable.getColumnModel().getColumn(3).setMinWidth(200);
            pointTable.getColumnModel().getColumn(3).setPreferredWidth(200);
            pointTable.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 650, 150));

        emailLabel.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 153, 0));
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 258, 250, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\anjan\\Desktop\\CIS\\Project\\GuessMyNumber\\src\\main\\java\\Resources\\GameProfileBackground.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EndPage endPage = new EndPage();
        endPage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameProfilePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameProfilePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameProfilePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameProfilePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameProfilePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel highLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pointTable;
    // End of variables declaration//GEN-END:variables
}
